GCTRealMate.exe "%~dp0\RSBE01.txt"
GCTRealMate.exe "%~dp0\BOOST.txt"
GCTRealMate.exe "%~dp0\NETPLAY.txt"
GCTRealMate.exe "%~dp0\NETBOOST.txt"
GCTRealMate.exe "%~dp0\DOUBLES.txt"
GCTRealMate.exe "%~dp0\DUBBOOST.txt"